from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.database import get_db
from app.trips.models import Trip
from app.stops.models import Stop
from app.activities.models import Activity
from app.auth.utils import get_current_user
from app.auth.models import User
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import cm
import io

router = APIRouter()

@router.get("/trips/{trip_id}/export/pdf")
async def export_trip_pdf(
    trip_id: str,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    # Get trip
    trip_result = await db.execute(select(Trip).where(Trip.id == trip_id))
    trip = trip_result.scalar_one_or_none()
    if not trip:
        raise HTTPException(404, "Trip not found")
    if str(trip.user_id) != str(current_user.id):
        raise HTTPException(403, "Access denied")

    # Get stops
    stops_result = await db.execute(
        select(Stop).where(Stop.trip_id == trip_id).order_by(Stop.order)
    )
    stops = stops_result.scalars().all()

    # Build PDF
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('title', fontSize=24, fontName='Helvetica-Bold',
                                  textColor=colors.HexColor('#6366f1'), spaceAfter=10)
    heading_style = ParagraphStyle('heading', fontSize=14, fontName='Helvetica-Bold',
                                    textColor=colors.HexColor('#1e293b'), spaceAfter=6)
    normal_style = styles['Normal']

    story = []

    # Title
    story.append(Paragraph(f"🗺 {trip.name}", title_style))
    story.append(Paragraph(f"{trip.start_date} → {trip.end_date}", normal_style))
    if trip.description:
        story.append(Spacer(1, 0.3*cm))
        story.append(Paragraph(trip.description, normal_style))
    story.append(Spacer(1, 0.8*cm))

    # Stops
    for i, stop in enumerate(stops):
        story.append(Paragraph(f"Stop {i+1}: {stop.city}, {stop.country}", heading_style))
        story.append(Paragraph(f"Dates: {stop.start_date} → {stop.end_date}", normal_style))
        if stop.budget:
            story.append(Paragraph(f"Budget: ₹{stop.budget:,.0f}", normal_style))

        # Activities
        acts_result = await db.execute(
            select(Activity).where(Activity.stop_id == stop.id).order_by(Activity.day)
        )
        activities = acts_result.scalars().all()

        if activities:
            story.append(Spacer(1, 0.3*cm))
            data = [["Activity", "Type", "Cost", "Duration"]]
            for a in activities:
                data.append([a.name, a.type, f"₹{a.cost:,.0f}", f"{a.duration_hours}h"])

            table = Table(data, colWidths=[7*cm, 3*cm, 3*cm, 3*cm])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#6366f1')),
                ('TEXTCOLOR', (0,0), (-1,0), colors.white),
                ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
                ('FONTSIZE', (0,0), (-1,-1), 9),
                ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#f1f5f9')]),
                ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
                ('PADDING', (0,0), (-1,-1), 6),
            ]))
            story.append(table)

        story.append(Spacer(1, 0.8*cm))

    # Footer
    story.append(Paragraph("Generated by Traveloop ✈",
                            ParagraphStyle('footer', fontSize=8, textColor=colors.grey)))

    doc.build(story)
    buffer.seek(0)

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={trip.name}.pdf"}
    )